%%{init:{'theme':'forest'}}%%

erDiagram
    series |o--o{ comic : "シリーズ名"
    %% magazine 雑誌に載らないストーリー、掲載がない号もある 雑誌連載はWeb連載時には分割されている
    magazine |o--o| story : "初出の掲載誌"
    %% story Web掲載された単話、「単行本に未収録」もあり
    story |o--|{ web_comic : "分割"
    %% web_comic ストーリー以外のWeb連載に登場した絵
    web_comic |o--o{ fragment : "その他の絵"
    comic |o--|{ story : "収録された巻"
    %% journey 第〇旅が前後編に分割されるケース 同じ場所が複数の旅に登場する場合あり
    journey ||--|{ story : "前後編"
    %% story その他雑多な絵に関連する単話
    story |o--o{ fragment : "関連する絵"
    story |o--o{ scene : ""
    story }|--|{ venue : ""
    story }|--|{ place : "ストーリー登場地点"
    %% camera_center_place ストーリー登場地点を含む領域(四角形)の中心座標
    place |o--|{ story : "領域"
    %% story 単話に登場する地点をルートとして表現する
    story }|--|{ route : "複数あり"
    place ||--|{ step : "順列あり"
    route ||--|{ step : "順列あり"
    venue ||--|{ place : ""
    comic }o--o{ venue : ""
    place |o--o{ fragment : ""
    place |o--o{ scene : ""
    place |o--o{ tweet : ""
    place |o--o{ photo : ""
    character }|--|{ place : ""
    character }|--o{ fragment : ""
    %% character 登場するキャラクター
    character }|--o{ scene : "登場"
    user |o--o{ tweet : ""
    user |o--o{ photo : ""
    %% group ユーザーは何れかのグループに所属する
    group }|--|{ user : "所属"


%% series 正シリーズと番外シリーズは、別々に登録する ※巻数が自然数の順列になる [リソース]
series {
    serial id PK
    %% 正確な作品の名称
    char title "作品名"
    %% 略称や通称で代表的なもの
    char short_title "略称"
    char author "著者名"
    %% 出版社 例：KADOKAWA
    char publisher "出版社"
    %% コミック・シリーズのレーベル名称 例：電撃コミックスNEXT
    char label "レーベル"
    %% 雑誌連載の誌名か、Web連載のレーベル名称
    char magazine_title "連載誌"
    %% 公式サイトや他のWebサイトから代表するものを1件
    url site "代表（公式）サイト"
    int rel_series_id "関係するシリーズ（単方向リスト）"
}

%% comic 単行本 1巻、2巻、…。単巻のみの場合はseries=NULL [リソース]
comic {
    serial id PK
    %% series comic
    rel series FK
    %% 第n巻
    int number
    %% 例：ざつ旅-That's Journey- 1
    char title "各巻タイトル"
    %% 特徴的な帯の文言
    char obi "オビ"
    %% 巻末の奥付にある、初版発行日
    date issued "発行日"
    date released "書店発売日"
    %% 版元ドットコムの書誌情報DBより
    url cover_image_url "書影url"
    char isbn "ISBN13"
    text memo
}

%% web_comic Web連載 第1旅(1)、番外旅、一枚モノ、… [リソース]
web_comic {
    serial id PK
    %% story web_comic
    rel story FK
    char title "各話の名前"
    int part_number "分割の順列"
    int pages "ページ数"
    url cw_url "Comic Walker"
    date cw_published
    url nico_url "ニコニコ静画"
    date nico_published
    text memo
}

%% magazine 雑誌連載 マオウ [イベント]
magazine {
    serial id PK
    %% 雑誌のタイトル 例：電撃マオウ 2020年1月号
    char title "タイトル"
    %% 書店等での発売日 ※タイトルの月の2か月前27日前後
    date released "発売日"
    char tag_line "表紙や付録になった号、などを表すタグ"
    url site
    url cover_image
    text memo
}

%% fragment その他媒体 表紙カラー、店舗特典、ポスター。コミック収録と未収録がある [リソース]
fragment {
    serial id PK
    %% story fragment
    rel story FK
    %% web_comic fragment
    rel web_comic FK
    %% character fragment
    rel character FK
    %% place fragment
    rel place FK
    char title
    url url
    text memo
}

%% journey 第〇旅、番外旅 [イベント]
journey {
    serial id PK
    int number
    char key
    %% 1:本編 2:番外旅 9:その他
    int type "タイプ"
    text memo
}

%% story 単行本の単話 第〇旅前編、第〇旅後編。コミック未収録もある [イベント]
story {
    serial id PK
    %% magazine story
    rel magazine FK
    %% comic story
    rel comic FK
    %% journey story
    rel journey FK
    char title
    char subtitle
    %% place story このストーリーに登場する主な地点をすべて包含するような範囲（四角形）の中心
    rel camera_center_place FK
    int camera_zoom_level
}

%% route 経路 placeを組み合わせて経路とする [リソース]
route {
    serial id PK
    %% story route
    rel story FK
    char name
    text memo
}

%% venue 目的地 会津、松島、那須、… [リソース]
venue {
    serial id PK
    %% story venue
    rel story FK
    %% comic venue
    rel comic FK
    char name
    %% 1:都道府県 2:市区町村 3:番地等の細かい行政界 5:著名観光地 6:ランドマーク、顕著な建造物、施設 7:道、航路、等
    int type ""
}

%% place 場所 東京駅の顔出しパネル、登場店舗、宿泊場所、観光名所、施設、交通拠点 [リソース]
place {
    serial id PK
    %% venue place
    rel venue FK
    %% story place
    rel story FK
    %% character place
    rel character FK
    char name
    char latitude
    char longitude
    char altitude
    text memo
}

%% step 訪問 routeに含まれる地点を訪れた日時 [イベント]
step {
    serial id PK
    %% route step
    rel route FK
    %% place step
    rel place FK
    int number
    datetime datetime
}

%% scene シーン 名シーン、ざつ旅ARのマーカー [イベント]
scene {
    serial id PK
    %% story scene
    rel story FK
    %% place scene
    rel place FK
    %% character scene
    rel character FK
    %% コミック掲載ページ
    int page "ページ"
    text memo
}

%% character キャラクター 主要5人、編集部、他 [リソース]
character {
    serial id PK
    char name
    char type
    text description
}

%% photo flickr (google place photo api有料) [リソース]
photo {
    serial id PK
    %% place photo
    rel place FK
    %% user photo
    rel user FK
    url url
    int width
    int height
}

%% tweet Twitter 石坂さん、鈴ヶ森さん、読者等、無関係 [リソース]
tweet {
    serial id PK
    %% user tweet
    rel user FK
    %% place tweet
    rel place FK
    int type
    url url
    text description
}

%% user ユーザー 利用者 [リソース]
user {
    serial id PK
    %% group user
    rel group FK
    char name
    int type
    text memo
}

%% group グループ [リソース]
group {
    serial id PK
    char name
    int visibility
    text memo
}

%% role [リソース]
%% permission 権限 [イベント]
